#import './DSSPeerEvent.gql'
#import './DSSRaiseResponse.gql'

type Query {
    hello: String
}

type Mutation {
    raise(event: DSSPeerEventInput) : DSSRaiseResponse,
}

type Subscription {
    connectionEvent(toID: ID): DSSPeerEvent,
}